<template>
  <div class="conversion-summary">
    <h1>This Vue.js app was generated by:<br>ng2vue-autoconverter<br>from anglarjs 'jfrog-vue-essentials' project</h1>
    <h2>Conversion Summary</h2>
    <div>Converted angularjs entities:</div>
    <div v-for="item in conversionSummary">
      {{ item }}
    </div>
  </div>
</template>

<script>
  import axios from 'axios';
  export default {
    name: 'Ng2VueConversionSummary',
    data () {
      return {
        conversionSummary: null
      }
    },
    mounted() {
      axios
        .get('conversionSummary.json')
        .then(response => {
          this.conversionSummary = response.data;
        })

    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
  .conversion-summary {
    position: absolute;
    width: 100%;
    background: aqua;
    top:0;
    bottom: 0;
    text-align: center;
  }
</style>
